# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://zzz032.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Yuelang's resume
# Description of the Site
description: This is Yuelang's resume
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

